"""添加relationship

Revision ID: bbad0ed2f9cf
Revises: 0843f02036a2
Create Date: 2020-10-09 11:21:57.959940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbad0ed2f9cf'
down_revision = '0843f02036a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
