"""添加relationship

Revision ID: d7ecc93cf8be
Revises: bbad0ed2f9cf
Create Date: 2020-10-09 11:25:30.694358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ecc93cf8be'
down_revision = 'bbad0ed2f9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
