"""添加relationship

Revision ID: f7f012eac1b0
Revises: d7ecc93cf8be
Create Date: 2020-10-09 11:27:25.737675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f012eac1b0'
down_revision = 'd7ecc93cf8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
